[project]
name = "karmabot"
version = "0.1.0"
requires-python = ">=3.13"
description = "A karma bot for Penguins Network."
license = "GPL3"
readme = "README.md"

dependencies = [
    "peewee==3.16.0",
    "python-decouple>=3.8",
    "python-telegram-bot[ext]>=22.5",
]

